model:
  base_learning_rate: 5.0e-05
  adjust_learning_rate: false
  find_unused_parameters: true
  gradient_clip_algorithm: norm
  precision: bf16
  grad_clip: 1.0
  grad_acc_steps: 1
  target: models.second_stage.fm_model.Model
  params:
    warmup_steps: 5000
    min_lr_multiplier: 0.1
    enc_scale: 2.841
    adjust_lr_to_batch_size: false
    num_pred_frames: 1
    tokenizer_config:
      folder: $TK_WORK_DIR/2025-08-20T21-18-10_stage1_vq_192x336_DLC101603_mixed_ft_dec_only
      ckpt_path: checkpoints/last.ckpt
    generator_config:
      target: networks.DiT.dit.STDiT
      params:
        max_num_frames: 64
        hidden_size: 768
        depth: 12
        num_heads: 12
        mlp_ratio: 4
        input_size:
        - 12
        - 21
        patch_size: 1
        in_channels: 16
        dropout: 0.0
        ctx_noise_aug_ratio: 0.1
        ctx_noise_aug_prob: 0.5
        drop_ctx_rate: 0.1
        causal_time_attn: true
data:
  target: data.datamodule.DataModuleFromConfig
  params:
    batch_size: 7
    num_workers: 0
    train:
    - target: data.custom_multiframe.MultiHDF5DatasetMultiFrameRandomizeFrameRate
      params:
        hdf5_paths_file: /work/dlcsmall1/dienertj-nuplan/nuplan_train_10Hz_640x360_images__90.txt
        hdf5_paths_file_odometry: /work/dlcsmall1/dienertj-nuplan/nuplan_train_10Hz_640x360_odometry__90.txt
        size:
        - 192
        - 336
        num_frames: 6
        stored_data_frame_rate: 5
        frame_rates_and_weights:
        - - 5
          - 1
        aug: random_shift
        scale_min: 0.15
        scale_max: 0.5
    validation:
      target: data.custom_multiframe.MultiHDF5DatasetMultiFrameRandomizeFrameRate
      params:
        hdf5_paths_file: /work/dlcsmall1/dienertj-nuplan/nuplan_train_10Hz_640x360_images__9.txt
        hdf5_paths_file_odometry: /work/dlcsmall1/dienertj-nuplan/nuplan_train_10Hz_640x360_odometry__9.txt
        size:
        - 192
        - 336
        num_frames: 6
        stored_data_frame_rate: 5
        frame_rates_and_weights:
        - - 5
          - 1
-t: null
-e: null
'30': null
