model:
  base_learning_rate: 5.0e-05
  adjust_learning_rate: false
  find_unused_parameters: true
  gradient_clip_algorithm: norm
  precision: bf16
  grad_clip: 1.0
  grad_acc_steps: 1
  target: models.second_stage.fm_model.Model
  params:
    # --- init from pre-trained Stage2 world model ---
    init_weights_path: $TK_WORK_DIR/logs_fm/2025-09-11T18-50-33_stage2_vq_if_192x336_DLC12406894/checkpoints/last.ckpt

    warmup_steps: 5000
    min_lr_multiplier: 0.1
    enc_scale: 4.0
    adjust_lr_to_batch_size: false
    num_pred_frames: 1

    # --- Stage1 tokenizer (VQ) ---
    tokenizer_config:
      folder: $TK_WORK_DIR/logs_tok/2025-08-20T21-17-41_stage1_vq_if_192x336_DLC101602_mixed_ft_dec_only
      ckpt_path: checkpoints/last.ckpt

    # --- Stage2 generator (world model) ---
    generator_config:
      target: networks.DiT.dit.STDiT
      params:
        max_num_frames: 6
        hidden_size: 768
        depth: 12
        num_heads: 12
        mlp_ratio: 4
        input_size:
          - 12
          - 21
        patch_size: 1
        in_channels: 16
        dropout: 0.0
        ctx_noise_aug_ratio: 0.1
        ctx_noise_aug_prob: 0.5
        drop_ctx_rate: 0.1
        causal_time_attn: true

data:
  target: data.datamodule.DataModuleFromConfig
  params:
    batch_size: 1          # you can increase if memory allows
    num_workers: 0
    size: [192, 336]
    train:
      - target: data.covla_dataset.CoVLAOrbisMultiFrame
        params:
          # core temporal + resolution settings
          num_frames: 6
          stored_data_frame_rate: 20
          target_frame_rate: 5
          size:
            - 192
            - 336

          # paths to your local CoVLA data
          captions_dir: /work/dlclarge2/alidemaa-text-control-orbis/orbis/data/covla_captions
          videos_dir: /work/dlclarge2/alidemaa-text-control-orbis/orbis/data/covla_100_videos

          # optional dataset knobs
          num_samples: null     # use all videos; set e.g. 100 for a subset
          debug: false
          aug: random_resize_center
          scale_min: 0.75
          scale_max: 1.0

    validation:
      target: data.covla_dataset.CoVLAOrbisMultiFrame
      params:
        # same settings as train; you can point to a separate val folder or subset
        num_frames: 6
        stored_data_frame_rate: 20
        target_frame_rate: 5
        size:
          - 192
          - 336

        captions_dir: /work/dlclarge2/alidemaa-text-control-orbis/orbis/data/covla_captions
        videos_dir: /work/dlclarge2/alidemaa-text-control-orbis/orbis/data/covla_100_videos

        num_samples: 50        # e.g. use 50 videos for validation; adjust as you like
        debug: false
        aug: random_resize_center
        scale_min: 0.75
        scale_max: 1.0
